# Task 7: Làm sạch & Khai phá dữ liệu với Pandas

Phần ghi chú và thực hành cá nhân cho Task 7 trong hoạt động AI Pioneer:
- Làm quen với cấu trúc `DataFrame` và `Series`
- Đọc dữ liệu từ CSV (`pd.read_csv`) và khảo sát ban đầu với `.shape`, `.info()`, `.describe()`
- Phát hiện và xử lý missing values (NaN) bằng `fillna` (median, mode) và `dropna`
- Lọc dữ liệu bằng điều kiện boolean, truy xuất với `loc`/`iloc`, sắp xếp với `sort_values`
- Gom nhóm và tổng hợp dữ liệu với `groupby` kết hợp `agg`
- Mini project EDA trên dataset Titanic (891 hành khách, 12 cột)

---
## Phần 1 – Import Pandas & DataFrame / Series

Hai cấu trúc dữ liệu chính của Pandas:
- **`DataFrame`**: bảng 2 chiều gồm các hàng và cột có nhãn, tương tự bảng Excel hoặc bảng SQL.
- **`Series`**: mảng 1 chiều có nhãn index – mỗi cột trong DataFrame thực chất là một Series.

Pandas tích hợp chặt với NumPy nên nhiều thao tác số trong Pandas cũng chạy dạng vector hóa, không cần loop.

In [1]:
# Import Pandas và NumPy theo quy ước chuẩn quốc tế
import pandas as pd
import numpy as np

print("Đã import thư viện thành công!")
print("Pandas version:", pd.__version__)
print("NumPy version :", np.__version__)

Đã import thư viện thành công!
Pandas version: 3.0.6
NumPy version : 2.4.6

---
## Phần 2 – Đọc file CSV với Pandas

- `pd.read_csv()`: đọc file CSV thành DataFrame.
- `df.head(n)` / `df.tail(n)`: xem nhanh n dòng đầu hoặc cuối bảng.

In [2]:
import os

# Đọc file titanic.csv từ thư mục data/
# (Hỗ trợ đường dẫn tương đối linh hoạt khi chạy trong notebook)
csv_path = "data/titanic.csv" if os.path.exists("data/titanic.csv") else "task7_pandas/data/titanic.csv"

df = pd.read_csv(csv_path)

print("Đã nạp file dữ liệu thành công!")
print("\n5 dòng đầu tiên của dataset (df.head()):")
df.head()

Đã nạp file dữ liệu thành công!

5 dòng đầu tiên của dataset (df.head()):

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [3]:
print("5 dòng cuối cùng của dataset (df.tail()):")
df.tail()

5 dòng cuối cùng của dataset (df.tail()):

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

---
## Phần 3 – Phân biệt DataFrame và Series

- `df["Age"]` (1 ngoặc vuông): trả về `Series` (1 chiều).
- `df[["Age"]]` (2 ngoặc vuông): trả về `DataFrame` (2 chiều, vẫn là bảng).
- `df[["Age", "Sex", "Fare"]]`: trích nhiều cột thành DataFrame con.

Điểm mình hay nhầm ban đầu là 1 ngoặc và 2 ngoặc cho kết quả khác kiểu dữ liệu.

In [4]:
# 1. Kiểm tra kiểu của bảng dữ liệu
print("Kiểu của df:", type(df))

# 2. Lấy một cột đơn lẻ
age_col = df["Age"]
print("Kiểu của df['Age']:", type(age_col), "-> Đây là 1 Series (1 chiều)")

# 3. Lấy nhiều cột cùng lúc
subset_cols = df[["Age", "Sex", "Fare"]]
print("Kiểu của df[['Age', 'Sex', 'Fare']]:", type(subset_cols), "-> Đây là 1 DataFrame (2 chiều)")

print("\n3 dòng đầu tiên của bảng con:")
subset_cols.head(3)

Kiểu của df: <class 'pandas.DataFrame'>
Kiểu của df['Age']: <class 'pandas.Series'> -> Đây là 1 Series (1 chiều)
Kiểu của df[['Age', 'Sex', 'Fare']]: <class 'pandas.DataFrame'> -> Đây là 1 DataFrame (2 chiều)

3 dòng đầu tiên của bảng con:

    Age     Sex     Fare
0  22.0    male   7.2500
1  38.0  female  71.2833
2  26.0  female   7.9250

In [5]:
# 4. Phân biệt rõ ràng giữa df['Age'] và df[['Age']]
print("Kích thước của df['Age']   :", df["Age"].shape, "  -> 1 chiều (Series)")
print("Kích thước của df[['Age']] :", df[["Age"]].shape, "-> 2 chiều: 891 hàng, 1 cột (DataFrame)")

Kích thước của df['Age']   : (891,)   -> 1 chiều (Series)
Kích thước của df[['Age']] : (891, 1) -> 2 chiều: 891 hàng, 1 cột (DataFrame)

---
## Phần 4 – Khảo sát cấu trúc dataset

Những lệnh mình chạy đầu tiên khi nhận một dataset mới:
- `df.shape`: trả về tuple `(số hàng, số cột)` – biết ngay kích thước bảng.
- `df.columns`: danh sách tên các cột.
- `df.dtypes`: kiểu dữ liệu từng cột.
- `df.info()`: tổng quan đầy đủ nhất – số hàng non-null từng cột, kiểu dữ liệu, bộ nhớ tiêu thụ; cũng là cách nhanh nhất để phát hiện cột nào đang bị thiếu dữ liệu.

In [6]:
print("=== KHẢO SÁT CẤU TRÚC DATASET ===")
print("1. df.shape  :", df.shape, "-> Dataset gồm", df.shape[0], "hàng và", df.shape[1], "cột")
print("\n2. df.columns:\n", list(df.columns))
print("\n3. df.index  :", df.index)
print("\n4. df.dtypes :\n", df.dtypes)

=== KHẢO SÁT CẤU TRÚC DATASET ===
1. df.shape  : (891, 12) -> Dataset gồm 891 hàng và 12 cột

2. df.columns:
 ['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked']

3. df.index  : RangeIndex(start=0, stop=891, step=1)

4. df.dtypes :
 PassengerId      int64
Survived         int64
Pclass           int64
Name               str
Sex                str
Age            float64
SibSp            int64
Parch            int64
Ticket             str
Fare           float64
Cabin              str
Embarked           str
dtype: object

In [7]:
print("5. df.info() - Bức tranh toàn cảnh về dữ liệu:")
df.info()

5. df.info() - Bức tranh toàn cảnh về dữ liệu:
<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

---
## Phần 5 – Thống kê mô tả với describe()

- `df.describe()`: tóm tắt các chỉ số thống kê cho cột số: `count`, `mean`, `std`, `min`, 25%, 50% (median), 75%, `max`.
- `df.describe(include="all")`: mở rộng sang cả cột phân loại, thêm `unique`, `top`, `freq`.

Mình thường dùng `describe()` để có cái nhìn đầu tiên về phân phối dữ liệu trước khi làm gì sâu hơn.

In [8]:
print("=== THỐNG KÊ CÁC CỘT SỐ (df.describe()) ===")
df.describe()

=== THỐNG KÊ CÁC CỘT SỐ (df.describe()) ===

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [9]:
print("=== THỐNG KÊ TOÀN BỘ CÁC CỘT (df.describe(include='all')) ===")
df.describe(include="all")

=== THỐNG KÊ TOÀN BỘ CÁC CỘT (df.describe(include='all')) ===

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
count,891.000000,891.000000,891.000000,891,891,714.000000,891.000000,891.000000,891,891.000000,204,889
unique,NaN,NaN,NaN,891,2,NaN,NaN,NaN,681,NaN,147,3
top,NaN,NaN,NaN,"Braund, Mr. Owen Harris",male,NaN,NaN,NaN,347082,NaN,G6,S
freq,NaN,NaN,NaN,1,577,NaN,NaN,NaN,7,NaN,4,644
mean,446.000000,0.383838,2.308642,NaN,NaN,29.699118,0.523008,0.381594,NaN,32.204208,NaN,NaN
std,257.353842,0.486592,0.836071,NaN,NaN,14.526497,1.102743,0.806057,NaN,49.693429,NaN,NaN
min,1.000000,0.000000,1.000000,NaN,NaN,0.420000,0.000000,0.000000,NaN,0.000000,NaN,NaN
25%,223.500000,0.000000,2.000000,NaN,NaN,20.125000,0.000000,0.000000,NaN,7.910400,NaN,NaN
50%,446.000000,0.000000,3.000000,NaN,NaN,28.000000,0.000000,0.000000,NaN,14.454200,NaN,NaN
75%,668.500000,1.000000,3.000000,NaN,NaN,38.000000,1.000000,0.000000,NaN,31.000000,NaN,NaN
max,891.000000,1.000000,3.000000,NaN,NaN,80.000000,8.000000,6.000000,NaN,512.329200,NaN,NaN

---
## Phần 6 – Đếm tần suất với value_counts()

- `df["cột"].value_counts()`: đếm số lần xuất hiện của từng giá trị trong cột phân loại.
- Thêm `normalize=True` để ra tỷ lệ phần trăm thay vì số lượng tuyệt đối.

In [10]:
print("=== 1. PHÂN BỐ GIỚI TÍNH (Sex) ===")
print("Số lượng tuyệt đối:")
print(df["Sex"].value_counts())
print("\nTỷ lệ phần trăm (%):")
print((df["Sex"].value_counts(normalize=True) * 100).round(2))

=== 1. PHÂN BỐ GIỚI TÍNH (Sex) ===
Số lượng tuyệt đối:
Sex
male      577
female    314
Name: count, dtype: int64

Tỷ lệ phần trăm (%):
Sex
male      64.76
female    35.24
Name: proportion, dtype: float64

In [11]:
print("=== 2. PHÂN BỐ HẠNG VÉ (Pclass: 1 = Nhất, 2 = Nhì, 3 = Ba) ===")
print(df["Pclass"].value_counts())
print("\nTỷ lệ phần trăm (%):")
print((df["Pclass"].value_counts(normalize=True) * 100).round(2))

=== 2. PHÂN BỐ HẠNG VÉ (Pclass: 1 = Nhất, 2 = Nhì, 3 = Ba) ===
Pclass
3    491
1    216
2    184
Name: count, dtype: int64

Tỷ lệ phần trăm (%):
Pclass
3    55.11
1    24.24
2    20.65
Name: proportion, dtype: float64

In [12]:
print("=== 3. PHÂN BỐ SỐNG SÓT (Survived: 0 = Mất, 1 = Sống sót) ===")
print(df["Survived"].value_counts())
print("\nTỷ lệ phần trăm sống sót toàn bộ:")
print((df["Survived"].value_counts(normalize=True) * 100).round(2))

=== 3. PHÂN BỐ SỐNG SÓT (Survived: 0 = Mất, 1 = Sống sót) ===
Survived
0    549
1    342
Name: count, dtype: int64

Tỷ lệ phần trăm sống sót toàn bộ:
Survived
0    61.62
1    38.38
Name: proportion, dtype: float64

---
## Phần 7 – Phát hiện dữ liệu thiếu (Missing Values)

`NaN` là ký hiệu cho ô dữ liệu bị thiếu. Cách mình kiểm tra:
- `df.isna().sum()`: đếm số ô NaN trên từng cột.
- `df.isna().mean() * 100`: tỷ lệ phần trăm thiếu từng cột – giúp quyết định chiến lược xử lý.

In [13]:
# Thống kê chi tiết missing value cho toàn bộ dataset
missing_count = df.isna().sum()
missing_percent = (df.isna().mean() * 100).round(2)

# Tạo bảng tổng hợp các cột bị thiếu
missing_df = pd.DataFrame({
    "Số lượng Missing": missing_count,
    "Tỷ lệ Missing (%)": missing_percent
})

# Lọc các cột có thiếu dữ liệu
missing_summary = missing_df[missing_df["Số lượng Missing"] > 0]

print("=== BẢNG THỐNG KÊ CÁC CỘT CÓ DỮ LIỆU THIẾU ===")
missing_summary

=== BẢNG THỐNG KÊ CÁC CỘT CÓ DỮ LIỆU THIẾU ===

          Số lượng Missing  Tỷ lệ Missing (%)
Age                    177              19.87
Cabin                  687              77.10
Embarked                 2               0.22

---
## Phần 8 – Xử lý dữ liệu thiếu

Mình copy sang `df_clean = df.copy()` trước khi làm gì – để giữ nguyên bản gốc, tránh bị đè dữ liệu.

Với từng cột trong Titanic, mình chọn cách xử lý theo lý do cụ thể:
- **Cột `Age`** (thiếu 177 ô): điền bằng **`median`** thay vì `mean`, vì median không bị kéo lệch bởi outlier (trẻ sơ sinh hoặc người rất già).
- **Cột `Embarked`** (thiếu 2 ô): điền bằng **`mode`** – giá trị xuất hiện nhiều nhất trong cột phân loại, ở đây là cảng `'S'` (Southampton).
- **Cột `Cabin`** (thiếu 687 ô, ~77%): mình drop cột này vì thiếu quá nhiều và không dùng cho các bước phân tích sau.

In [14]:
# Tạo bản copy an toàn
df_clean = df.copy()

# Minh họa lý do không nên lạm dụng dropna() trên toàn bộ dataset
df_dropped_demo = df.dropna()
print("Số dòng ban đầu     :", df.shape[0])
print("Số dòng nếu dropna():", df_dropped_demo.shape[0], "-> Mất", df.shape[0] - df_dropped_demo.shape[0], "dòng (quá lãng phí dữ liệu!)")

# 1. Xử lý cột Age: Điền bằng median
age_median = df_clean["Age"].median()
df_clean["Age"] = df_clean["Age"].fillna(age_median)
print(f"\n1. Đã điền NaN cột Age bằng median = {age_median}")

# 2. Xử lý cột Embarked: Điền bằng mode
embarked_mode = df_clean["Embarked"].mode()[0]
df_clean["Embarked"] = df_clean["Embarked"].fillna(embarked_mode)
print(f"2. Đã điền NaN cột Embarked bằng mode = '{embarked_mode}'")

# 3. Xử lý cột Cabin: Bỏ cột vì thiếu > 77% dữ liệu
df_clean = df_clean.drop(columns=["Cabin"])
print("3. Đã xóa cột Cabin do tỷ lệ thiếu vượt quá 77%")

# Kiểm tra lại số lượng missing values sau xử lý
print("\n=== SỐ LƯỢNG MISSING VALUES SAU KHI LÀM SẠCH ===")
print(df_clean.isna().sum())

Số dòng ban đầu     : 891
Số dòng nếu dropna(): 183 -> Mất 708 dòng (quá lãng phí dữ liệu!)

1. Đã điền NaN cột Age bằng median = 28.0
2. Đã điền NaN cột Embarked bằng mode = 'S'
3. Đã xóa cột Cabin do tỷ lệ thiếu vượt quá 77%

=== SỐ LƯỢNG MISSING VALUES SAU KHI LÀM SẠCH ===
PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

---
## Phần 9 – Lọc dữ liệu bằng điều kiện (Boolean Filtering)

Cú pháp: `df[điều kiện boolean]`. Khi kết hợp nhiều điều kiện:
- Phép VÀ: dùng `&` (không dùng từ khóa `and`).
- Phép HOẶC: dùng `|` (không dùng từ khóa `or`).
- Mỗi điều kiện phải bọc trong cặp ngoặc đơn `()`.

In [15]:
# 1. Hành khách trên 30 tuổi
over_30 = df[df["Age"] > 30]
print("1. Số hành khách trên 30 tuổi:", len(over_30))

# 2. Hành khách là nữ (female)
females = df[df["Sex"] == "female"]
print("2. Số hành khách nữ          :", len(females))

# 3. Hành khách nữ VÀ trên 30 tuổi
females_over_30 = df[(df["Sex"] == "female") & (df["Age"] > 30)]
print("3. Số hành khách nữ trên 30 tuổi:", len(females_over_30))

# 4. Hành khách thuộc hạng vé Pclass 1
pclass_1 = df[df["Pclass"] == 1]
print("4. Số hành khách hạng Pclass 1  :", len(pclass_1))

# 5. Hành khách có giá vé (Fare) lớn hơn giá vé trung bình
fare_mean = df["Fare"].mean()
above_avg_fare = df[df["Fare"] > fare_mean]
print(f"5. Số hành khách có Fare > trung bình ({fare_mean:.2f}):", len(above_avg_fare))

print("\nVí dụ 3 dòng đầu của nhóm Fare > trung bình:")
above_avg_fare[["Name", "Pclass", "Fare"]].head(3)

1. Số hành khách trên 30 tuổi: 305
2. Số hành khách nữ          : 314
3. Số hành khách nữ trên 30 tuổi: 103
4. Số hành khách hạng Pclass 1  : 216
5. Số hành khách có Fare > trung bình (32.20): 211

Ví dụ 3 dòng đầu của nhóm Fare > trung bình:

                                                Name  Pclass     Fare
1  Cumings, Mrs. John Bradley (Florence Briggs Th...       1  71.2833
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)       1  53.1000
6                            McCarthy, Mr. Timothy J       1  51.8625

---
## Phần 10 – Truy xuất với loc và iloc

- `loc[hàng, cột]`: lấy theo **nhãn** (tên cột, tên index).
- `iloc[hàng, cột]`: lấy theo **vị trí số nguyên** (index từ 0).

Điểm cần nhớ: `loc` bao gồm cả điểm cuối của range, còn `iloc` thì không (giống Python slicing thông thường).

In [16]:
print("=== 1. TRUY XUẤT BẰNG loc (Dựa vào tên nhãn và tên cột) ===")
loc_demo = df.loc[0:5, ["Name", "Age", "Sex"]]
loc_demo

=== 1. TRUY XUẤT BẰNG loc (Dựa vào tên nhãn và tên cột) ===

                                                Name   Age     Sex
0                            Braund, Mr. Owen Harris  22.0    male
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0  female
2                             Heikkinen, Miss. Laina  26.0  female
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0  female
4                           Allen, Mr. William Henry  35.0    male
5                                   Moran, Mr. James   NaN    male

In [17]:
print("=== 2. TRUY XUẤT BẰNG iloc (Dựa vào vị trí số nguyên) ===")
iloc_demo = df.iloc[0:5, 0:4]
iloc_demo

=== 2. TRUY XUẤT BẰNG iloc (Dựa vào vị trí số nguyên) ===

,PassengerId,Survived,Pclass,Name
0,1,0,3,"Braund, Mr. Owen Harris"
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th..."
2,3,1,3,"Heikkinen, Miss. Laina"
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)"
4,5,0,3,"Allen, Mr. William Henry"

---
## Phần 11 – Sắp xếp dữ liệu với sort_values()

- `sort_values(by="cột", ascending=True)`: tăng dần (mặc định).
- `sort_values(by="cột", ascending=False)`: giảm dần.
- Có thể truyền list cột để sắp xếp theo nhiều tiêu chí cùng lúc.

In [18]:
# 1. Sắp xếp Age tăng dần (Hành khách nhỏ tuổi nhất lên đầu)
print("Top 3 hành khách nhỏ tuổi nhất (Age tăng dần):")
df.sort_values("Age", ascending=True)[["Name", "Age", "Pclass"]].head(3)

Top 3 hành khách nhỏ tuổi nhất (Age tăng dần):

                                Name   Age  Pclass
803  Thomas, Master. Assad Alexander  0.42       3
755        Hamalainen, Master. Viljo  0.67       2
644           Baclini, Miss. Eugenie  0.75       3

In [19]:
# 2. Sắp xếp Fare giảm dần (Giá vé đắt nhất lên đầu)
print("Top 3 hành khách có giá vé đắt nhất (Fare giảm dần):")
df.sort_values("Fare", ascending=False)[["Name", "Fare", "Pclass"]].head(3)

Top 3 hành khách có giá vé đắt nhất (Fare giảm dần):

                                   Name      Fare  Pclass
679  Cardeza, Mr. Thomas Drake Martinez  512.3292       1
258                    Ward, Miss. Anna  512.3292       1
737              Lesurer, Mr. Gustave J  512.3292       1

In [20]:
# 3. Sắp xếp kết hợp: Pclass tăng dần, Fare giảm dần
print("Sắp xếp Pclass tăng dần, sau đó Fare giảm dần:")
df.sort_values(["Pclass", "Fare"], ascending=[True, False])[["Pclass", "Name", "Fare"]].head(5)

Sắp xếp Pclass tăng dần, sau đó Fare giảm dần:

     Pclass                                Name      Fare
258       1                    Ward, Miss. Anna  512.3292
679       1  Cardeza, Mr. Thomas Drake Martinez  512.3292
737       1              Lesurer, Mr. Gustave J  512.3292
27        1      Fortune, Mr. Charles Alexander  263.0000
88        1          Fortune, Miss. Mabel Helen  263.0000

---
## Phần 12 – Gom nhóm dữ liệu với groupby()

Mình dùng `groupby` để chia dữ liệu thành từng nhóm rồi tính thống kê cho mỗi nhóm. Cơ chế hoạt động theo 3 bước: **Split** (chia nhóm) → **Apply** (tính toán) → **Combine** (ghép kết quả lại).

Trong Titanic mình dùng phần này để xem tỷ lệ sống sót theo giới tính và Pclass.

In [21]:
print("=== 1. TỶ LỆ SỐNG THEO GIỚI TÍNH ===")
# Tính mean của cột Survived (vì Survived gồm 0 và 1, mean chính là tỷ lệ sống)
surv_by_sex = df.groupby("Sex")["Survived"].mean() * 100
print(surv_by_sex.round(2))

print("\n=== 2. TỶ LỆ SỐNG THEO HẠNG VÉ (Pclass) ===")
surv_by_pclass = df.groupby("Pclass")["Survived"].mean() * 100
print(surv_by_pclass.round(2))

print("\n=== 3. TUỔI TRUNG BÌNH THEO GIỚI TÍNH ===")
age_by_sex = df.groupby("Sex")["Age"].mean()
print(age_by_sex.round(2))

print("\n=== 4. GIÁ VÉ (FARE) TRUNG BÌNH THEO HẠNG VÉ ===")
fare_by_pclass = df.groupby("Pclass")["Fare"].mean()
print(fare_by_pclass.round(2))

=== 1. TỶ LỆ SỐNG THEO GIỚI TÍNH ===
Sex
female    74.20
male      18.89
Name: Survived, dtype: float64

=== 2. TỶ LỆ SỐNG THEO HẠNG VÉ (Pclass) ===
Pclass
1    62.96
2    47.28
3    24.24
Name: Survived, dtype: float64

=== 3. TUỔI TRUNG BÌNH THEO GIỚI TÍNH ===
Sex
female    27.92
male      30.73
Name: Age, dtype: float64

=== 4. GIÁ VÉ (FARE) TRUNG BÌNH THEO HẠNG VÉ ===
Pclass
1    84.15
2    20.66
3    13.68
Name: Fare, dtype: float64

---
## Phần 13 – Tính nhiều chỉ số với agg()

`agg()` cho phép tính nhiều hàm thống kê cùng lúc trên một hoặc nhiều cột. Ví dụ: tính cả `mean` tỷ lệ sống, `median` tuổi và `count` số hành khách theo Pclass chỉ trong một lệnh.

In [22]:
# 1. Tính count, mean, min, max của cột Age theo Sex
print("=== 1. THỐNG KÊ TUỔI THEO GIỚI TÍNH ===")
df.groupby("Sex")["Age"].agg(["count", "mean", "min", "max"]).round(2)

=== 1. THỐNG KÊ TUỔI THEO GIỚI TÍNH ===

        count   mean   min   max
Sex
female    261  27.92  0.75  63.0
male      453  30.73  0.42  80.0

In [23]:
# 2. Tính các chỉ số khác nhau trên các cột khác nhau theo Pclass
print("=== 2. TỔNG HỢP NHIỀU CỘT THEO HẠNG VÉ (Pclass) ===")
df.groupby("Pclass").agg({
    "Age": ["mean", "median"],
    "Fare": ["mean", "max"],
    "Survived": "mean"
}).round(2)

=== 2. TỔNG HỢP NHIỀU CỘT THEO HẠNG VÉ (Pclass) ===

          Age          Fare         Survived
         mean median   mean     max     mean
Pclass
1       38.23   37.0  84.15  512.33     0.63
2       29.88   29.0  20.66   73.50     0.47
3       25.14   24.0  13.68   69.55     0.24

---
## Phần 14 – Tạo thêm cột mới

Tạo thêm các đặc trưng từ dữ liệu có sẵn:
- `FamilySize`: `SibSp + Parch + 1` (tổng số thành viên gia đình trên tàu, kể cả bản thân).
- `IsAlone`: `True` nếu `FamilySize == 1` (đi một mình).

In [24]:
# Thêm cột FamilySize vào df_clean
df_clean["FamilySize"] = df_clean["SibSp"] + df_clean["Parch"] + 1

# Thêm cột IsAlone (True nếu đi một mình, False nếu đi cùng gia đình)
df_clean["IsAlone"] = (df_clean["FamilySize"] == 1)

print("=== MẪU DỮ LIỆU SAU KHI TẠO CỘT MỚI ===")
df_clean[["Name", "SibSp", "Parch", "FamilySize", "IsAlone"]].head()

=== MẪU DỮ LIỆU SAU KHI TẠO CỘT MỚI ===

,Name,SibSp,Parch,FamilySize,IsAlone
0,"Braund, Mr. Owen Harris",1,0,2,False
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,0,2,False
2,"Heikkinen, Miss. Laina",0,0,1,True
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,0,2,False
4,"Allen, Mr. William Henry",0,0,1,True

In [25]:
print("Tỷ lệ hành khách đi một mình trên tàu:")
print((df_clean["IsAlone"].value_counts(normalize=True) * 100).round(2))

Tỷ lệ hành khách đi một mình trên tàu:
IsAlone
True     60.27
False    39.73
Name: proportion, dtype: float64

---
## Phần 15 – Kiểm tra dòng trùng lặp (Duplicates)

`df.duplicated().sum()`: đếm số dòng trùng lặp hoàn toàn. Với Titanic, kết quả là **0 dòng trùng**. Nếu có, dùng `df.drop_duplicates()` để loại bỏ.

In [26]:
num_dup = df.duplicated().sum()
print("Số lượng dòng trùng lặp trong Titanic dataset:", num_dup)

if num_dup > 0:
    df_no_dup = df.drop_duplicates()
    print("Đã loại bỏ duplicate, shape mới:", df_no_dup.shape)
else:
    print("-> Không có dòng nào bị trùng lặp hoàn toàn trong dataset này!")

Số lượng dòng trùng lặp trong Titanic dataset: 0
-> Không có dòng nào bị trùng lặp hoàn toàn trong dataset này!

---
## Phần 16 – Mini Project: Khai phá dữ liệu (EDA) Titanic

Áp dụng tất cả các bước đã học vào dataset Titanic – từ load dữ liệu, làm sạch missing values, đến groupby và thống kê để rút ra nhận xét từ số liệu thực tế.

In [27]:
# 1. Load dataset
df_eda = pd.read_csv(csv_path)

# 2. Hiển thị shape
print("1 & 2. Shape ban đầu của dataset:", df_eda.shape)

# 3. Kiểm tra missing values
print("\n3. Missing values ban đầu:\n", df_eda.isna().sum())

# 4. Xử lý Age bằng median
df_eda["Age"] = df_eda["Age"].fillna(df_eda["Age"].median())

# 5. Xử lý Embarked bằng mode
df_eda["Embarked"] = df_eda["Embarked"].fillna(df_eda["Embarked"].mode()[0])

# 6. Bỏ Cabin do thiếu > 77%
df_eda = df_eda.drop(columns=["Cabin"])
print("\n4, 5, 6. Đã xử lý xong dữ liệu thiếu! Missing values sau xử lý:\n", df_eda.isna().sum())

1 & 2. Shape ban đầu của dataset: (891, 12)

3. Missing values ban đầu:
 PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

4, 5, 6. Đã xử lý xong dữ liệu thiếu! Missing values sau xử lý:
 PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

In [28]:
# 7. Tính số hành khách nam/nữ
print("7. Số hành khách nam/nữ:\n", df_eda["Sex"].value_counts())

# 8. Tính tỷ lệ sống toàn bộ
overall_survival_rate = df_eda["Survived"].mean()
print(f"\n8. Tỷ lệ sống sót toàn bộ dataset: {overall_survival_rate * 100:.2f}%")

# 9. Tính tỷ lệ sống theo Sex
print("\n9. Tỷ lệ sống theo Sex (%):\n", (df_eda.groupby("Sex")["Survived"].mean() * 100).round(2))

# 10. Tính tỷ lệ sống theo Pclass
print("\n10. Tỷ lệ sống theo Pclass (%):\n", (df_eda.groupby("Pclass")["Survived"].mean() * 100).round(2))

# 11 & 12. Tuổi trung bình & Fare trung bình
print(f"\n11. Tuổi trung bình : {df_eda['Age'].mean():.2f}")
print(f"12. Fare trung bình : {df_eda['Fare'].mean():.2f}")

7. Số hành khách nam/nữ:
 Sex
male      577
female    314
Name: count, dtype: int64

8. Tỷ lệ sống sót toàn bộ dataset: 38.38%

9. Tỷ lệ sống theo Sex (%):
 Sex
female    74.20
male      18.89
Name: Survived, dtype: float64

10. Tỷ lệ sống theo Pclass (%):
 Pclass
1    62.96
2    47.28
3    24.24
Name: Survived, dtype: float64

11. Tuổi trung bình : 29.36
12. Fare trung bình : 32.20

In [29]:
# 13. Tìm hành khách có Fare cao nhất
max_fare_passenger = df_eda.loc[df_eda["Fare"].idxmax()]
print(f"13. Hành khách có Fare cao nhất: {max_fare_passenger['Name']} (Fare: {max_fare_passenger['Fare']})")

# 14. Tìm hành khách lớn tuổi nhất
max_age_passenger = df_eda.loc[df_eda["Age"].idxmax()]
print(f"14. Hành khách lớn tuổi nhất: {max_age_passenger['Name']} (Tuổi: {max_age_passenger['Age']})")

# 15 & 16. Tạo FamilySize và tính trung bình
df_eda["FamilySize"] = df_eda["SibSp"] + df_eda["Parch"] + 1
print(f"\n15 & 16. FamilySize trung bình: {df_eda['FamilySize'].mean():.2f}")

# 17. Sắp xếp top 10 hành khách có Fare cao nhất
print("\n17. Top 10 hành khách có Fare cao nhất:")
df_eda.sort_values("Fare", ascending=False)[["Name", "Pclass", "Age", "Fare", "Survived"]].head(10)

13. Hành khách có Fare cao nhất: Ward, Miss. Anna (Fare: 512.3292)

14. Hành khách lớn tuổi nhất: Barkworth, Mr. Algernon Henry Wilson (Tuổi: 80.0)

15 & 16. FamilySize trung bình: 1.90

17. Top 10 hành khách có Fare cao nhất:

,Name,Pclass,Age,Fare,Survived
679,"Cardeza, Mr. Thomas Drake Martinez",1,36.0,512.3292,1
258,"Ward, Miss. Anna",1,35.0,512.3292,1
737,"Lesurer, Mr. Gustave J",1,35.0,512.3292,1
88,"Fortune, Miss. Mabel Helen",1,23.0,263.0000,1
438,"Fortune, Mr. Mark",1,64.0,263.0000,0
341,"Fortune, Miss. Alice Elizabeth",1,24.0,263.0000,1
27,"Fortune, Mr. Charles Alexander",1,19.0,263.0000,0
742,"Ryerson, Miss. Susan Parker ""Suzette""",1,21.0,262.3750,1
311,"Ryerson, Miss. Emily Borie",1,18.0,262.3750,1
299,"Baxter, Mrs. James (Helene DeLaudeniere Chaput)",1,50.0,247.5208,1

In [30]:
# 18. Tạo bảng groupby tổng hợp chi tiết theo Sex và Pclass
print("18. Bảng groupby tổng hợp theo Sex và Pclass:")
summary = df_eda.groupby(["Sex", "Pclass"]).agg(
    passenger_count=("PassengerId", "count"),
    average_age=("Age", "mean"),
    average_fare=("Fare", "mean"),
    survival_rate=("Survived", "mean")
).round(2)

summary

18. Bảng groupby tổng hợp theo Sex và Pclass:

               passenger_count  average_age  average_fare  survival_rate
Sex    Pclass
female 1                    94        33.98        106.13           0.97
       2                    76        28.70         21.97           0.92
       3                   144        23.57         16.12           0.50
male   1                   122        39.00         67.23           0.37
       2                   108        30.51         19.74           0.16
       3                   347        26.91         12.66           0.14

---
## Phần 17 – Nhận xét dựa trên kết quả thực hành

Những gì mình quan sát được từ dataset Titanic sau khi chạy các bước phân tích:

1. **Quy mô và làm sạch dữ liệu:**
   - Dataset có **891 dòng**, **12 cột**.
   - Cột `Cabin` thiếu 687 ô (~77%) → drop.
   - Cột `Age` thiếu 177 ô → điền median = 28.0.
   - Cột `Embarked` thiếu 2 ô → điền mode = `'S'`.
   - Không có dòng trùng lặp (0 duplicates).

2. **Tỷ lệ sống sót chung:**
   - **38.38%** hành khách sống sót – tức là khoảng hơn 1/3.

3. **Theo Giới tính:**
   - Nữ: **74.20%** sống sót.
   - Nam: **18.89%** sống sót.
   - Dữ liệu cho thấy chênh lệch lớn giữa hai nhóm.

4. **Theo Hạng vé (Pclass):**
   - Pclass 1: **62.96%** (giá vé TB $84.15).
   - Pclass 2: **47.28%** (giá vé TB $20.66).
   - Pclass 3: **24.24%** (giá vé TB $13.68).
   - Tỷ lệ sống sót giảm dần từ hạng 1 xuống hạng 3.

5. **Kết hợp Giới tính & Hạng vé:**
   - Nhóm có tỷ lệ cao nhất: Nữ Hạng 1 (**96.81%**) và Nữ Hạng 2 (**92.11%**).
   - Nhóm có tỷ lệ thấp nhất: Nam Hạng 3 (**13.54%**).

6. **Tuổi và giá vé:**
   - Tuổi trung bình: **29.36 tuổi**, cao nhất là 80 tuổi.
   - Giá vé trung bình: **$32.20**, cao nhất là $512.33.

---
## Phần 18 – Bài tập thực hành thêm

- **Bài 1:** Đếm tổng số hành khách dưới 18 tuổi.
- **Bài 2:** Tính giá vé trung bình (`Fare.mean()`) của hành khách nữ thuộc Pclass 1.
- **Bài 3:** Tìm Pclass có độ tuổi trung bình cao nhất.
- **Bài 4:** Lấy thông tin 5 hành khách lớn tuổi nhất.
- **Bài 5:** Tính tỷ lệ sống sót của hành khách dưới 18 tuổi.
- **Bài 6:** Groupby theo `Sex` và `Pclass`, đếm số hành khách mỗi nhóm.
- **Bài 7:** Tạo cột `AgeGroup` phân loại: Child (<12), Teen (12–17), Adult (18–59), Senior (≥60).

In [31]:
# === Ô THỰC HÀNH CỦA BẠN CHO BÀI 1, 2, 3 ===
# Viết code của bạn ở đây:

In [32]:
# === Ô THỰC HÀNH CỦA BẠN CHO BÀI 4, 5, 6, 7 ===
# Viết code của bạn ở đây:

---
### Code giải bài tập

In [33]:
print("=== ĐÁP ÁN BÀI 1: ĐẾM SỐ HÀNH KHÁCH DƯỚI 18 TUỔI ===")
under_18_count = (df_clean["Age"] < 18).sum()
print("Số hành khách dưới 18 tuổi:", under_18_count)

print("\n=== ĐÁP ÁN BÀI 2: FARE TRUNG BÌNH CỦA NỮ Ở PCLASS 1 ===")
female_pclass1_fare = df_clean[(df_clean["Sex"] == "female") & (df_clean["Pclass"] == 1)]["Fare"].mean()
print(f"Giá vé trung bình của nữ hạng 1: ${female_pclass1_fare:.2f}")

print("\n=== ĐÁP ÁN BÀI 3: PCLASS CÓ TUỔI TRUNG BÌNH CAO NHẤT ===")
age_by_pclass = df_clean.groupby("Pclass")["Age"].mean()
highest_age_pclass = age_by_pclass.idxmax()
print(age_by_pclass.round(2))
print(f"-> Hạng vé có tuổi trung bình cao nhất là Pclass: {highest_age_pclass}")

print("\n=== ĐÁP ÁN BÀI 4: 5 HÀNH KHÁCH LỚN TUỔI NHẤT ===")
top5_oldest = df_clean.sort_values("Age", ascending=False)[["Name", "Sex", "Age", "Pclass"]].head(5)
display(top5_oldest)

print("\n=== ĐÁP ÁN BÀI 5: TỶ LỆ SỐNG CỦA HÀNH KHÁCH DƯỚI 18 TUỔI ===")
under_18_survival = df_clean[df_clean["Age"] < 18]["Survived"].mean() * 100
print(f"Tỷ lệ sống của hành khách < 18 tuổi: {under_18_survival:.2f}%")

print("\n=== ĐÁP ÁN BÀI 6: GROUPBY SEX VÀ PCLASS ĐỂ ĐẾM SỐ HÀNH KHÁCH ===")
count_by_sex_pclass = df_clean.groupby(["Sex", "Pclass"])["PassengerId"].count()
print(count_by_sex_pclass)

print("\n=== ĐÁP ÁN BÀI 7: TẠO CỘT PHÂN LOẠI NHÓM TUỔI (AgeGroup) ===")
bins = [0, 12, 18, 60, 120]
labels = ["Child", "Teen", "Adult", "Senior"]
df_clean["AgeGroup"] = pd.cut(df_clean["Age"], bins=bins, labels=labels, right=False)
print("Số lượng hành khách theo từng nhóm tuổi:")
print(df_clean["AgeGroup"].value_counts())
display(df_clean[["Name", "Age", "AgeGroup"]].head(5))

=== ĐÁP ÁN BÀI 1: ĐẾM SỐ HÀNH KHÁCH DƯỚI 18 TUỔI ===
Số hành khách dưới 18 tuổi: 113

=== ĐÁP ÁN BÀI 2: FARE TRUNG BÌNH CỦA NỮ Ở PCLASS 1 ===
Giá vé trung bình của nữ hạng 1: $106.13

=== ĐÁP ÁN BÀI 3: PCLASS CÓ TUỔI TRUNG BÌNH CAO NHẤT ===
Pclass
1    36.81
2    29.77
3    25.93
Name: Age, dtype: float64
-> Hạng vé có tuổi trung bình cao nhất là Pclass: 1

=== ĐÁP ÁN BÀI 4: 5 HÀNH KHÁCH LỚN TUỔI NHẤT ===

                                     Name   Sex   Age  Pclass
630  Barkworth, Mr. Algernon Henry Wilson  male  80.0       1
851                   Svensson, Mr. Johan  male  74.0       3
96              Goldschmidt, Mr. George B  male  71.0       1
493               Artagaveytia, Mr. Ramon  male  71.0       1
116                  Connors, Mr. Patrick  male  70.5       3

=== ĐÁP ÁN BÀI 5: TỶ LỆ SỐNG CỦA HÀNH KHÁCH DƯỚI 18 TUỔI ===
Tỷ lệ sống của hành khách < 18 tuổi: 53.98%

=== ĐÁP ÁN BÀI 6: GROUPBY SEX VÀ PCLASS ĐỂ ĐẾM SỐ HÀNH KHÁCH ===

Sex     Pclass
female  1          94
        2          76
        3         144
male    1         122
        2         108
        3         347
Name: PassengerId, dtype: int64

=== ĐÁP ÁN BÀI 7: TẠO CỘT PHÂN LOẠI NHÓM TUỔI (AgeGroup) ===
Số lượng hành khách theo từng nhóm tuổi:
AgeGroup
Adult     752
Child      68
Teen       45
Senior     26
Name: count, dtype: int64

                                                Name   Age AgeGroup
0                            Braund, Mr. Owen Harris  22.0    Adult
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0    Adult
2                             Heikkinen, Miss. Laina  26.0    Adult
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0    Adult
4                           Allen, Mr. William Henry  35.0    Adult

---
## Phần 19 – Tóm tắt nhanh kiến thức Task 7

Những thao tác mình đã làm quen qua task này:
- Phân biệt `DataFrame` (bảng 2D) và `Series` (cột 1D).
- Khảo sát ban đầu: `shape`, `info()`, `describe()`, `value_counts()`.
- Phát hiện missing values: `isna().sum()`.
- Điền NaN: `fillna(median)` cho cột số, `fillna(mode[0])` cho cột phân loại.
- Lọc điều kiện boolean với `&`, `|` và ngoặc đơn bắt buộc.
- Truy xuất dữ liệu: `loc` theo nhãn, `iloc` theo vị trí số.
- Sắp xếp: `sort_values()`.
- Gom nhóm: `groupby()` kết hợp `agg()`.
- Kiểm tra trùng lặp: `duplicated().sum()`.